name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master    

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
        #   tags: alvarogv19/python-app:latest
          tags: alvarogv19/${{values.app_name}}:${{  '${{ github.sha }}'  }}
    outputs:
      commit_id: ${{  '${{ github.sha }}'  }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - 
        name: Modify values file
        shell: bash
        run: |
          COMMIT_ID="${{ '{{' }} needs.ci.outputs.commit_id ${{ '}}' }}"
          echo "Debug: El commit ID es $COMMIT_ID"
          echo "${{ '"${{needs.ci.outputs.commit_id}}'  }}"
          # Actualizar e instalar python3 y pip
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
          # Instalar yq (la versi√≥n de python se llama habitualmente yq)
          # Usamos --break-system-packages si el runner usa una distro moderna (Debian 12+)
          pip3 install yq --break-system-packages || pip3 install yq
          
          # Verificar instalaciones
          python3 --version
          yq --version
          # Variables de Backstage puras (sin el $ dentro de las llaves)
          # Asignar el tag (escapando la sintaxis de GitHub Actions)
          TAG=${{ '${{ needs.ci.outputs.commit_id }}' }}
          # Variables de Backstage puras (sin el $ dentro de las llaves)
          FILE_PATH="charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml"

          echo "Actualizando archivo: $FILE_PATH"
          yq -i -Y ".image.tag = \"$COMMIT_ID\"" "$FILE_PATH"

      - 
        name: Github push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'
      -
        name: Argocd install
        shell: bash
        run: |
          curl -k -sSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd:443 \
            --insecure \
            --username admin \
            --password "${{ '${{ secrets.ARGOCD_PASSWORD }}' }}" \
            --grpc-web
          argocd app sync ${{values.app_name}}