name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master    

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
        #   tags: alvarogv19/python-app:latest
          tags: alvarogv19/${{values.app_name}}:${{  '${{ github.sha }}'  }}
    outputs:
      commit_id: ${{  '${{ github.sha }}'  }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Modify values file
        shell: bash
        run: |
          # 1. Definimos el tag de forma limpia
          TAG="${{ '${{ needs.ci.outputs.commit_id }}' }}"
          FILE="charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml"

          echo "Actualizando $FILE con el tag $TAG"

          # 2. Instalamos yq (versi√≥n de Python)
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install yq --break-system-packages || pip3 install yq

          yq -i -Y ".image.tag = \"$TAG\"" "$FILE"
      - 
        name: Github push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'
      -
        name: Argocd install
        shell: bash
        run: |
          curl -k -sSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd:443 \
            --insecure \
            --username admin \
            --password "${{ '${{ secrets.ARGOCD_PASSWORD }}' }}" \
            --grpc-web

      - name: Argocd check repo and app
        shell: bash
        run: |
          # Check if repo exists or create it
          repo="https://github.com/agvas123-org/${{values.app_name}}.git"
          argocd repo list | grep $repo || argocd repo add $repo

          # Argocd create app
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-namespace ${{values.app_env}} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.app_env}}.yaml \
            --revision master \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      -
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd:443 \
            --insecure \
            --username admin \
            --password "${{ '${{ secrets.ARGOCD_PASSWORD }}' }}" \
            --grpc-web
            

            argocd app sync ${{values.app_name}}
            argocd app wait ${{values.app_name}} --timeout 180